import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../../shared/ui/Card';
import { Button } from '../../shared/ui/Button';
import { Input } from '../../shared/ui/Input';
import { useCreateOrder } from '../../data/hooks/useOrders';
import { useServices } from '../../data/hooks/useServices';
import { useCustomers, useCreateCustomer } from '../../data/hooks/useCustomers';
import { formatCurrency } from '../../shared/utils';
import { CheckCircle2 } from 'lucide-react';

export function POSScreen() {
  const [customerPhone, setCustomerPhone] = useState('');
  const [customerName, setCustomerName] = useState('');
  const [cart, setCart] = useState<{ serviceId: string; qty: number }[]>([]);
  const [isReturningCustomer, setIsReturningCustomer] = useState(false);
  const [showSuggestions, setShowSuggestions] = useState(false);
  
  const createOrder = useCreateOrder();
  const createCustomer = useCreateCustomer();
  const { data: services = [], isLoading: isLoadingServices } = useServices();
  const { data: customers = [] } = useCustomers();

  // Remove the old useEffect and replace with simple exact match check
  useEffect(() => {
    const exactMatch = customers.find(c => c.phone === customerPhone);
    setIsReturningCustomer(!!exactMatch);
  }, [customerPhone, customers]);

  const handleSelectCustomer = (c: any) => {
    setCustomerPhone(c.phone);
    setCustomerName(c.name);
    setIsReturningCustomer(true);
    setShowSuggestions(false);
  };

  const suggestions = customers.filter(c => {
    if (!customerPhone && !customerName) return false;
    // Don't show suggestion if it's already an exact match
    if (c.phone === customerPhone && c.name === customerName) return false;
    
    const phoneMatch = customerPhone && c.phone.includes(customerPhone);
    const nameMatch = customerName && c.name.toLowerCase().includes(customerName.toLowerCase());
    
    return phoneMatch || nameMatch;
  }).slice(0, 5);

  const addToCart = (serviceId: string) => {
    setCart(prev => {
      const existing = prev.find(item => item.serviceId === serviceId);
      if (existing) {
        return prev.map(item => item.serviceId === serviceId ? { ...item, qty: item.qty + 1 } : item);
      }
      return [...prev, { serviceId, qty: 1 }];
    });
  };

  const subtotal = cart.reduce((sum, item) => {
    const service = services.find(s => s.id === item.serviceId);
    return sum + (service?.price || 0) * item.qty;
  }, 0);
  const tax = 0;
  const total = subtotal + tax;

  const handleCheckout = async () => {
    if (!customerPhone || cart.length === 0) return;

    try {
      let currentCustomerId = 'c_new';
      
      // Check if customer exists or create a new one
      const existingCustomer = customers.find(c => c.phone === customerPhone);

      if (existingCustomer) {
        currentCustomerId = existingCustomer.id;
      } else {
        const newCustomer = await createCustomer.mutateAsync({
          name: customerName || 'عميل نقدي',
          phone: customerPhone
        });
        currentCustomerId = newCustomer.id;
      }

      const items = cart.flatMap(cartItem => {
        const service = services.find(s => s.id === cartItem.serviceId)!;
        return Array.from({ length: cartItem.qty }).map((_, i) => ({
          id: Math.random().toString(36).substring(7),
          tagCode: `PENDING-${i}`, // Will be generated by backend
          serviceId: service.id,
          serviceName: service.name,
          status: 'PENDING' as const,
          price: service.price,
        }));
      });

      await createOrder.mutateAsync({
        customerId: currentCustomerId,
        customerName: customerName || 'عميل نقدي',
        customerPhone,
        status: 'RECEIVED',
        priority: 'NORMAL',
        totals: { subtotal, tax, discount: 0, total, paid: 0, balance: total },
        itemCount: items.length,
        items,
        dueAt: new Date(Date.now() + 86400000).toISOString(), // +24 hours
      });

      // Reset form
      setCart([]);
      setCustomerPhone('');
      setCustomerName('');
      setIsReturningCustomer(false);
      alert('تم إنشاء الطلب بنجاح!');
    } catch (error: any) {
      console.error('Error creating order:', error);
      alert('حدث خطأ أثناء إنشاء الطلب. يرجى التأكد من الصلاحيات والمحاولة مرة أخرى.');
    }
  };

  return (
    <div className="p-4 md:p-8 h-full flex flex-col overflow-auto lg:overflow-hidden">
      <div className="mb-6 shrink-0">
        <h2 className="text-2xl font-bold tracking-tight">نقطة البيع (الكاشير)</h2>
        <p className="text-slate-500">إنشاء طلبات جديدة وإدارة العملاء.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 flex-1 lg:min-h-0 pb-6 lg:pb-0">
        {/* Left: Services Catalog */}
        <div className="lg:col-span-2 flex flex-col gap-6 lg:overflow-auto">
          <Card className="shrink-0">
            <CardHeader>
              <CardTitle>بيانات العميل</CardTitle>
            </CardHeader>
            <CardContent className="flex flex-col sm:flex-row gap-4 relative">
              <div className="flex-1">
                <label className="text-xs font-medium text-slate-500 mb-1 block">رقم الهاتف</label>
                <Input 
                  placeholder="+968 9000 0000" 
                  value={customerPhone} 
                  onChange={e => {
                    setCustomerPhone(e.target.value);
                    setShowSuggestions(true);
                  }} 
                  onFocus={() => setShowSuggestions(true)}
                  dir="ltr"
                  className="text-right"
                />
              </div>
              <div className="flex-1">
                <label className="text-xs font-medium text-slate-500 mb-1 flex items-center justify-between">
                  <span>الاسم (اختياري)</span>
                  {isReturningCustomer && (
                    <span className="text-emerald-600 flex items-center gap-1 text-[10px] font-bold bg-emerald-50 px-2 py-0.5 rounded-full">
                      <CheckCircle2 size={12} />
                      عميل مسجل
                    </span>
                  )}
                </label>
                <Input 
                  placeholder="اسم العميل" 
                  value={customerName} 
                  onChange={e => {
                    setCustomerName(e.target.value);
                    setShowSuggestions(true);
                  }} 
                  onFocus={() => setShowSuggestions(true)}
                  className={isReturningCustomer ? "border-emerald-200 bg-emerald-50/30" : ""}
                />
              </div>

              {/* Suggestions Dropdown */}
              {showSuggestions && suggestions.length > 0 && (
                <div className="absolute top-full left-0 right-0 mt-2 bg-white rounded-xl shadow-lg border border-slate-200 overflow-hidden z-10 w-full sm:w-[calc(100%-2rem)] sm:mx-4">
                  <div className="px-3 py-2 bg-slate-50 border-b border-slate-100 text-xs font-medium text-slate-500">
                    العملاء المقترحين
                  </div>
                  <ul>
                    {suggestions.map((c) => (
                      <li key={c.id}>
                        <button
                          type="button"
                          className="w-full text-right px-4 py-3 hover:bg-slate-50 transition-colors flex justify-between items-center border-b border-slate-100 last:border-0"
                          onClick={() => handleSelectCustomer(c)}
                        >
                          <span className="font-medium text-slate-900">{c.name}</span>
                          <span className="font-mono text-sm text-slate-500" dir="ltr">{c.phone}</span>
                        </button>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </CardContent>
          </Card>

          <Card className="flex-1 shrink-0">
            <CardHeader>
              <CardTitle>الخدمات</CardTitle>
            </CardHeader>
            <CardContent>
              {isLoadingServices ? (
                <div className="text-center text-slate-500 py-8">جاري تحميل الخدمات...</div>
              ) : (
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
                  {services.map(service => (
                    <button
                      key={service.id}
                      onClick={() => addToCart(service.id)}
                      className="p-4 rounded-xl border border-slate-200 hover:border-slate-900 hover:shadow-md transition-all text-right flex flex-col justify-between h-28 sm:h-32 bg-slate-50/50"
                    >
                      <span className="font-medium text-slate-900 text-sm sm:text-base">{service.name}</span>
                      <span className="text-slate-500 font-mono text-sm" dir="ltr">{formatCurrency(service.price)}</span>
                    </button>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Right: Cart */}
        <Card className="flex flex-col h-[400px] lg:h-full shrink-0">
          <CardHeader className="border-b border-slate-100 shrink-0">
            <CardTitle>الطلب الحالي</CardTitle>
          </CardHeader>
          <CardContent className="flex-1 overflow-auto p-0">
            {cart.length === 0 ? (
              <div className="h-full flex items-center justify-center text-slate-400 text-sm">
                السلة فارغة
              </div>
            ) : (
              <ul className="divide-y divide-slate-100">
                {cart.map(item => {
                  const service = services.find(s => s.id === item.serviceId)!;
                  return (
                    <li key={item.serviceId} className="p-4 flex justify-between items-center">
                      <div>
                        <p className="font-medium text-sm">{service.name}</p>
                        <p className="text-xs text-slate-500" dir="ltr">{formatCurrency(service.price)} x {item.qty}</p>
                      </div>
                      <div className="font-mono text-sm" dir="ltr">
                        {formatCurrency(service.price * item.qty)}
                      </div>
                    </li>
                  );
                })}
              </ul>
            )}
          </CardContent>
          <div className="p-4 sm:p-6 bg-slate-50 border-t border-slate-100 rounded-b-xl space-y-3 shrink-0">
            <div className="flex justify-between text-sm text-slate-500">
              <span>المجموع الفرعي</span>
              <span className="font-mono" dir="ltr">{formatCurrency(subtotal)}</span>
            </div>
            <div className="flex justify-between text-lg font-bold text-slate-900 pt-2 border-t border-slate-200">
              <span>الإجمالي</span>
              <span className="font-mono" dir="ltr">{formatCurrency(total)}</span>
            </div>
            <Button 
              className="w-full mt-4" 
              size="lg" 
              disabled={cart.length === 0 || !customerPhone || createOrder.isPending}
              onClick={handleCheckout}
            >
              {createOrder.isPending ? 'جاري المعالجة...' : 'إنشاء الطلب'}
            </Button>
          </div>
        </Card>
      </div>
    </div>
  );
}
